I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 167, in script
    jump choice6_done
ScriptError: could not find label 'choice6_done'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 167, in script
    jump choice6_done
  File "C:\Users\clim7253.HWDSB\AppData\Local\Microsoft\WinGet\Packages\RenPy.RenPySDK_Microsoft.Winget.Source_8wekyb3d8bbwe\renpy-8.3.7-sdk\renpy\ast.py", line 1712, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\clim7253.HWDSB\AppData\Local\Microsoft\WinGet\Packages\RenPy.RenPySDK_Microsoft.Winget.Source_8wekyb3d8bbwe\renpy-8.3.7-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'choice6_done'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Storyboard 1.0
Sun Sep 28 05:46:06 2025
